vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.tabstop = 4               -- show existing tab with 4 spaces width
vim.opt.softtabstop = 4           -- show existing tab with 4 spaces width
vim.opt.shiftwidth = 4            -- when identing with '>', use 4 spaces width
vim.opt.expandtab = true          -- on pressing tab, insert 4 spaces
vim.opt.smarttab = true           -- insert tabs on the start of a line according to shiftwidth
vim.opt.smartindent = true        -- automatically inserts one extra level of indentation in some cases
vim.opt.hidden = true             -- Hides the current buffer when a new file is openned
vim.opt.incsearch = true          -- incremental search
vim.opt.ignorecase = true         -- ignore case in search
vim.opt.smartcase = true          -- consider case if there is a upper case character
vim.opt.scrolloff = 8             -- minimum number of lines to keep above and below the cursor
vim.opt.colorcolumn = '89'        -- draws a line at the given line to keep aware of the line size
vim.opt.signcolumn = 'yes'        -- add a column on the left. Useful for linting
vim.opt.cmdheight = 2             -- give more space for displaying messages
vim.opt.updatetime = 100          -- time in miliseconds to consider the changes
vim.opt.encoding = 'utf-8'        -- the enconding should be utf-8 to activate the font icons
vim.opt.backup = false            -- no backup files
vim.opt.writebackup = false       -- no backup files
vim.opt.splitright = true         -- create the vertical splits to the right
vim.opt.splitbelow = true         -- create the horizontal splits below
vim.opt.foldmethod = 'indent'
vim.opt.filetype = 'on'
vim.opt.termguicolors = true
vim.g.mapleader = ' '
vim.g.maplocalleader = ','
vim.g.python3_host_prog = '/usr/bin/python3'
